# Generated by Django 4.0.3 on 2023-03-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('catalog_number', models.CharField(max_length=255)),
                ('sub_and_cat', models.CharField(default='', max_length=255)),
                ('class_section', models.CharField(max_length=255)),
                ('class_number', models.CharField(max_length=255)),
                ('class_title', models.CharField(max_length=500)),
                ('instructor', models.CharField(max_length=500)),
            ],
        ),
    ]
