# Generated by Django 4.1.5 on 2023-03-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("catalog_number", models.CharField(max_length=255)),
                ("class_section", models.CharField(max_length=255)),
                ("class_number", models.IntegerField()),
                ("class_title", models.CharField(max_length=255)),
                ("class_topic_formal_desc", models.CharField(max_length=255)),
                ("instructor", models.CharField(max_length=255)),
                ("enrollment_capacity", models.IntegerField()),
                ("meeting_days", models.CharField(max_length=255)),
                ("meeting_time_start", models.TimeField()),
                ("meeting_time_end", models.TimeField()),
                ("term", models.CharField(max_length=255)),
                ("term_desc", models.CharField(max_length=255)),
            ],
        ),
    ]
