# Generated by Django 4.1.5 on 2023-05-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_student_true",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
