# Generated by Django 4.1.7 on 2023-03-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sub_and_cat',
            field=models.CharField(default='', max_length=255),
        ),
    ]
