# Generated by Django 4.1.7 on 2023-03-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_session'),
        ('myapp', '0002_user'),
    ]

    operations = [
    ]
