# Generated by Django 4.1.7 on 2023-03-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_course_sub_and_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_number',
            field=models.CharField(max_length=255),
        ),
    ]
