# Generated by Django 4.1.5 on 2023-05-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_appuser_is_student_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_student",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
