# Generated by Django 4.1.7 on 2023-03-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_course_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(max_length=500),
        ),
    ]
