# Generated by Django 4.1.7 on 2023-03-31 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_merge_0002_session_0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='title',
            new_name='class_title',
        ),
    ]
