# Generated by Django 4.1.7 on 2023-03-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_title_session_class_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_and_cat',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
