# Generated by Django 4.1.5 on 2023-04-02 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_course_id_alter_course_sub_and_cat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="class_title",
        ),
        migrations.AddField(
            model_name="session",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.course",
            ),
        ),
    ]
