# Generated by Django 4.0.3 on 2023-04-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('DECLINED', 'Declined')], default='PENDING', max_length=8),
        ),
    ]
